version: '3'
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    links:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  redis-proxy:
    build:
      context: .
    links:
      - redis
    ports:
      - 8080:8080
    command: redis-proxy --http-host 0.0.0.0 --redis-host redis --cache-capacity 100 --cache-ttl 0
